// noticedata.js
export const notices = [
  {
    id: 1,
    title: "Call for Papers: International Water Conference 2025",
    date: "2025-05-10",
    link: "https://example.com/conference2025",
    isNew: true,
  },
  {
    id: 2,
    title: "Lab Safety Training Scheduled for June 2025",
    date: "2025-05-01",
    link: "https://example.com/safety-training",
    isNew: true,
  },
  {
    id: 3,
    title: "New Research Grant Awarded to Dr. Anshul Yadav",
    date: "2025-04-15",
    link: "https://example.com/research-grant",
    isNew: false,
  },
  {
    id: 4,
    title: "Workshop on Membrane Technology – Registration Open",
    date: "2025-04-20",
    link: "https://example.com/workshop-membrane",
    isNew: false,
  },
  {
    id: 5,
    title: "Annual Water Treatment Symposium – Save the Date",
    date: "2025-05-12",
    link: "https://example.com/symposium-2025",
    isNew: true,
  },
  {
    id: 6,
    title: "Publication: Advances in CFD Modelling for Wastewater",
    date: "2025-03-30",
    link: "https://example.com/publication-cfd",
    isNew: false,
  },
  {
    id: 7,
    title: "Job Opening: Research Assistant Position",
    date: "2025-05-05",
    link: "https://example.com/job-opening",
    isNew: true,
  },
  {
    id: 8,
    title: "Guest Lecture by Prof. Smith on Sustainable Water Use",
    date: "2025-04-25",
    link: "https://example.com/guest-lecture",
    isNew: false,
  },
  {
    id: 9,
    title: "Monthly Group Meeting – May 2025",
    date: "2025-05-07",
    link: "https://example.com/monthly-meeting",
    isNew: true,
  },
  {
    id: 10,
    title: "Student Paper Competition – Submission Deadline Extended",
    date: "2025-04-28",
    link: "https://example.com/paper-competition",
    isNew: false,
  },
];
export const upcomingevents = [
  {
    id: 1,
    title: "Call for Papers: International Water Conference 2025",
    date: "2025-05-10",
    link: "https://example.com/conference2025",
    isNew: true,
  },
  {
    id: 2,
    title: "Workshop on Advanced Water Treatment Technologies",
    date: "2025-06-15",
    link: "https://example.com/workshop-water-treatment",
    isNew: false,
  },
  {
    id: 3,
    title: "Guest Lecture by Dr. Sharma on Membrane Filtration",
    date: "2025-07-02",
    link: "https://example.com/guest-lecture-sharma",
    isNew: true,
  },
  {
    id: 4,
    title: "Webinar: Latest Trends in Wastewater Management",
    date: "2025-07-20",
    link: "https://example.com/webinar-wastewater",
    isNew: false,
  },
  {
    id: 5,
    title: "Annual Lab Open House and Demo Day",
    date: "2025-08-05",
    link: "https://example.com/open-house",
    isNew: false,
  },
];
