
export const publications = {
  journalArticles: [
    {
      id: 'pub-01',
      type: 'journal',
      title: 'Advances in membrane distillation for wastewater treatment: Innovations, challenges, and sustainable opportunities',
      authors: ['R.V.Patel', 'A.Yadav', 'V.K.Shahi'], 
      journal: 'Science of the Total Environment',
      year: 2025,
      volume: '969',
      pages: '178749',
      citescore:'16.4',
    impact_factor:'8.2',
    quartile:'Q1',
      image: '/images/research/journal/advances.jpeg',
      link: 'https://www.sciencedirect.com/science/article/abs/pii/S0048969725003833',
      publisher: 'Elsevier',
      featured: true
    },
    {
      id: 'pub-02',
      type: 'journal',
      title: 'Chemical grafting of hydrophobic functional groups on polyvinylidene fluoride side chain for vacuum membrane distillation applications',
      authors: ['R.V.Patel', 'S.Chaubey', 'A.Yadav', 'V.K.Shahi'],
      journal: 'Journal of Environmental Chemical Engineering',
      year: 2024,
      volume: '12',
      pages: '112746',
      citescore:'12.5',
      impact_factor:'7.4',
    quartile:'Q1',
    image: '/images/research/journal/chemical.jpeg',
    link: 'https://www.sciencedirect.com/science/article/abs/pii/S2213343724008765',
      publisher: 'Elsevier',
      featured: true
    },
    {
      id: 'pub-03',
      type: 'journal',
      title: 'Carbon chain grafted polyvinylidene fluoride membranes for textile water remediation: Experimental and computational studies',
      authors: ['R.V.Patel', 'S.Chaubey', 'A.Yadav', 'B.G.Vyas', 'V.K.Shahi'],
      journal: 'Chemical Engineering Journal',
      year: 2025,
      volume: '509',
      pages: '160965',
     citescore:'20.6',
      impact_factor:'13.4',
    quartile:'Q1',
    image: '/images/research/journal/carbon.png',
    link: 'https://www.sciencedirect.com/science/article/abs/pii/S1385894725017863',
      publisher: 'Elsevier',
      featured: true
    },
    {
      id: 'pub-05',
      type: 'journal',
      title: 'Adsorptive removal of norfloxacin from water using polyvinylidene fluoride-boron nitride nanosheets mixed matrix membrane: Insights from experiments and molecular dynamics simulation',
      authors: ['P.Awasthi', 'A.Yadav', 'N.Sinha'],
      journal: 'Journal of Environmental Chemical Engineering',
      year: 2025,
      volume: '13',
      pages: '115783',
      citescore:'12.5',
      impact_factor:'7.4',
    quartile:'Q1',
    image: '/images/research/journal/chemical.jpeg',
    link: 'https://www.sciencedirect.com/science/article/abs/pii/S2213343725004786',
      publisher: 'Elsevier',
      featured: false
    },
    {
      id: 'pub-06',
      type: 'journal',
      title: 'Side-chain grafted functional groups poly(vinylidene fluoride-hexafluoropropylene) anti-fouling fluorinated polymer membrane with tuneable hydrophobicity for distillation',
      authors: ['A.Yadav', 'K.Singh', 'V.K.Shahi'],
      journal: 'Desalination',
      year: 2022,
      volume: '525',
      pages: '115501',
      citescore:'14.3',
      impact_factor:'8.4',
    quartile:'Q1',
    image: '/images/research/journal/desalinations.jpg',
    link: 'https://www.sciencedirect.com/science/article/abs/pii/S0011916421005725',
      publisher: 'Elsevier',
      featured: true
    },
    {
      id: 'pub-07',
      type: 'journal',
      title: 'Investigations on the effect of spacer in direct contact and air gap membrane distillation using computational fluid dynamics',
      authors: ['A.Yadav', 'C.P.Singh', 'R.V.Patel', 'A.Kumar', 'P.K.Labhasetwar'],
      journal: 'Colloids and Surfaces A: Physicochemical and Engineering Aspects',
      year: 2022,
      volume: '654',
      pages: '130111',
      citescore:'9.6',
      impact_factor:'4.9',
    quartile:'Q1',
    image: '/images/research/journal/colloids_654.jpg',
    link: 'https://www.sciencedirect.com/science/article/abs/pii/S0927775722018660',
      publisher: 'Elsevier',
      featured: false
    },
    {
      id: 'pub-08',
      type: 'journal',
      title: 'Hexagonal boron nitride nanosheets incorporated photocatalytic polyvinylidene fluoride mixed matrix membranes for textile wastewater treatment via vacuum-assisted distillation',
      authors: ['A.Yadav', 'R.V.Patel', 'P.Awasthi', 'N.Sinha', 'P.K.Labhasetwar'],
      journal: 'Colloids and Surfaces A: Physicochemical and Engineering Aspects',
      year: 2022,
      volume: '653',
      pages: '129955',
      citescore:'9.6',
      impact_factor:'4.9',
    quartile:'Q1',
    image: '/images/research/journal/colloids_653.jpg',
    link: 'https://www.sciencedirect.com/science/article/abs/pii/S0927775722017101',
      publisher: 'Elsevier',
      featured: false
    },
    {
      id: 'pub-09',
      type: 'journal',
      title: 'Recovery of CaSO4 and NaCl from sub-soil brine using CNT@MOF5 incorporated poly(vinylidene fluoride-hexafluoropropylene) membranes via vacuum-assisted distillation',
      authors: ['A.Yadav', 'R.V.Patel', 'B.G.Vyas', 'P.K.Labhasetwar', 'V.K.Shahi'],
      journal: 'Colloids and Surfaces A: Physicochemical and Engineering Aspects',
      year: 2022,
      volume: '645',
      pages: '128918',
    citescore:'9.6',
      impact_factor:'4.9',
    quartile:'Q1',
    image: '/images/research/journal/colloids_645.jpg',
    link: 'https://www.sciencedirect.com/science/article/abs/pii/S0927775722006732',
      publisher: 'Elsevier',
      featured: false
    },
    {
      id: 'pub-10',
      type: 'journal',
      title: 'Experimental study and numerical optimization for removal of methyl orange using polytetrafluoroethylene membranes in vacuum membrane distillation process',
      authors: ['A.Yadav', 'R.V.Patel', 'C.P.Singh', 'P.K.Labhasetwar', 'V.K.Shahi'],
      journal: 'Colloids and Surfaces A: Physicochemical and Engineering Aspects',
      year: 2022,
      volume: '635',
      pages: '128070',
      citescore:'9.6',
      impact_factor:'4.9',
    quartile:'Q1',
    image: '/images/research/journal/colloids_635.jpg',
    link: 'https://www.sciencedirect.com/science/article/abs/pii/S0927775721019397',
      publisher: 'Elsevier',
      featured: false
    },
    {
      id: 'pub-11',
      type: 'journal',
      title: 'Structural tailoring of ceria nanoparticles for fabricating fouling resistant nanocomposite membranes with high flux distillation',
      authors: ['A.Yadav', 'J.R.Mandal', 'A.B.Panda', 'V.K.Shahi'],
      journal: 'Colloids and Surfaces A: Physicochemical and Engineering Aspects',
      year: 2022,
      volume: '633',
      pages: '127858',
      citescore:'9.6',
      impact_factor:'4.9',
    quartile:'Q1',
    image: '/images/research/journal/colloids_633.jpg',
    link: 'https://www.sciencedirect.com/science/article/abs/pii/S0927775721017271',
      publisher: 'Elsevier',
      featured: false
    },
    {
      id: 'pub-12',
      type: 'journal',
      title: 'Computational fluid dynamics based numerical simulations of heat transfer, fluid flow and mass transfer in vacuum membrane distillation process',
      authors: ['A.Yadav', 'C.P.Singh', 'R.V.Patel', 'P.K.Labhasetwar', 'V.K.Shahi'],
      journal: 'Water Supply',
      year: 2022,
      volume: '22',
      pages: '6262-6280',
      citescore:'N/A',
      impact_factor:'1.9',
    quartile:'Q2',
    image: '/images/research/journal/computational.jpg',
    link: 'https://iwaponline.com/ws/article/22/7/6262/88697/Computational-fluid-dynamics-based-numerical',
      publisher: 'International Water Association',
      featured: false
    },
    {
      id: 'pub-13',
      type: 'journal',
      title: 'Membrane distillation crystallization technology for zero liquid discharge and resource recovery: Opportunities, challenges and futuristic perspectives',
      authors: ['A.Yadav', 'P.K.Labhasetwar', 'V.K.Shahi'],
      journal: 'Science of The Total Environment',
      year: 2022,
      volume: '806',
      pages: '150692',
      citescore:'16.4',
      impact_factor:'8.2',
    quartile:'Q1',
    image: '/images/research/journal/membrane_806.jpg',
    link: 'https://www.sciencedirect.com/science/article/abs/pii/S0048969721057703',
      publisher: 'Elsevier',
      featured: true
    },
    {
      id: 'pub-14',
      type: 'journal',
      title: 'Membrane distillation crystallization for simultaneous recovery of water and salt from tannery industry wastewater using TiO2 modified poly(vinylidene fluoride-co-hexafluoropropylene) nanocomposite membranes',
      authors: ['A.Yadav', 'K.Singh', 'A.B.Panda', 'P.K.Labhasetwar', 'V.K.Shahi'],
      journal: 'Journal of Water Process Engineering',
      year: 2021,
      volume: '44',
      pages: '102393',
      citescore:'9.6',
      impact_factor:'6.3',
    quartile:'Q1',
    image: '/images/research/journal/membrane_44.jpg',
    link: 'https://www.sciencedirect.com/science/article/abs/pii/S2214714421004803',
      publisher: 'Elsevier',
      featured: true
    },
    {
      id: 'pub-15',
      type: 'journal',
      title: 'Novel MIL101(Fe) impregnated poly(vinylidene fluoride-co-hexafluoropropylene) mixed matrix membranes for dye removal from textile industry wastewater',
      authors: ['A.Yadav', 'R.V.Patel', 'P.K.Labhasetwar', 'V.K.Shahi'],
      journal: 'Journal of Water Process Engineering',
      year: 2021,
      volume: '43',
      pages: '102317',
      citescore:'9.6',
      impact_factor:'6.3',
    quartile:'Q1',
    image: '/images/research/journal/water_43.jpg',
    link: 'https://www.sciencedirect.com/science/article/abs/pii/S2214714421004049',
      publisher: 'Elsevier',
      featured: false
    },
    {
      id: 'pub-16',
      type: 'journal',
      title: 'CNT functionalized ZIF-8 impregnated poly(vinylidene fluoride-co-hexafluoropropylene) mixed matrix membranes for antibiotics removal from pharmaceutical industry wastewater by vacuum membrane distillation',
      authors: ['A.Yadav', 'P.Yadav', 'P.K.Labhasetwar', 'V.K.Shahi'],
      journal: 'Journal of Environmental Chemical Engineering',
      year: 2021,
      volume: '9',
      pages: '106560',
      citescore:'12.5',
      impact_factor:'7.4',
    quartile:'Q1',
    image: '/images/research/journal/chemical_9.jpg',
    link: 'https://www.sciencedirect.com/science/article/abs/pii/S2213343721015372',
      publisher: 'Elsevier',
      featured: false
    },
    {
      id: 'pub-17',
      type: 'journal',
      title: 'Photocatalytic TiO2 incorporated PVDF-co-HFP UV-cleaning mixed matrix membranes for effective removal of dyes from synthetic wastewater system via membrane distillation',
      authors: ['A.Yadav', 'P.Sharma', 'A.B.Panda', 'V.K.Shahi'],
      journal: 'Journal of Environmental Chemical Engineering',
      year: 2021,
      volume: '9',
      pages: '105904',
      citescore:'12.5',
      impact_factor:'7.4',
    quartile:'Q1',
    image: '/images/research/journal/chemical_9.jpg',
    link: 'https://www.sciencedirect.com/science/article/abs/pii/S2213343721008812',
      publisher: 'Elsevier',
      featured: false
    },
    {
      id: 'pub-18',
      type: 'journal',
      title: 'Membrane distillation using low-grade energy for desalination: A review',
      authors: ['A.Yadav', 'P.K.Labhasetwar', 'V.K.Shahi'],
      journal: 'Journal of Environmental Chemical Engineering',
      year: 2021,
      volume: '9',
      pages: '105818',
      citescore:'12.5',
      impact_factor:'7.4',
    quartile:'Q1',
    image: '/images/research/journal/chemical_9.jpg',
    link: 'https://www.sciencedirect.com/science/article/abs/pii/S2213343721007958',
      publisher: 'Elsevier',
      featured: true
    },
    {
      id: 'pub-19',
      type: 'journal',
      title: 'Fabrication and optimization of tunable pore size poly(ethylene glycol) modified poly(vinylidene-co-hexafluoropropylene) membranes in vacuum membrane distillation for desalination',
      authors: ['A.Yadav', 'P.K.Labhasetwar', 'V.K.Shahi'],
      journal: 'Separation and Purification Technology',
      year: 2021,
      volume: '271',
      pages: '118840',
      citescore:'15.1',
      impact_factor:'8.2',
    quartile:'Q1',
    image: '/images/research/journal/seperation.jpg',
    link: 'https://www.sciencedirect.com/science/article/abs/pii/S1383586621005529',
      publisher: 'Elsevier',
      featured: false
    },
    
  ]

,
  conferences: [
    {
    id: 'conf-01',
    type: 'conference',
    title: null,
    authors: null,
    conference: null,
    year: null,
    location: null,
    publisher: null,
    featured: false
  }
  ],
 books: [
   {
    id: 'book-01',
    title: 'Membrane-based point-of-use drinking water treatment systems',
    authors: ['P.K. Labhasetwar', 'A.Yadav'],
    image: '/images/research/books/membre_book.jpeg',
    publisher: 'International Water Association Publishing',
    year: 2023,
    link: 'https://iwaponline.com/ebooks/book/867/Membrane-Based-Point-of-Use-Drinking-Water',
    isbn: '9781789062717',
    eisbn: '9781789062724',
    doi: '',
    featured: true
  },
  { id: 'book-02',
   title: 'Applications of two-dimensional nanomaterials for water and wastewater treatment',
   authors: ['A.Yadav', 'R. Yadav', 'P.K. Labhasetwar'],
   image: '/images/research/books/application_book.jpg',
   publisher: 'Apple Academic Publishers, CRC Press',
  year: 2026,
  link: 'https://www.appleacademicpress.com/applications-of-two-dimensional-nanomaterials-in-water-and-wastewater-treatment-/9781779642967',
  isbn: '9781779642967',
  eisbn: '9781779642974',
  doi: '',
  featured: true },
  {
  id: 'book-02',
  title: 'Computational techniques for simulating and optimizing membrane processes for (waste)water treatment',
  authors: ['A.Yadav', 'P.K. Labhasetwar'],
  image: '', 
  publisher: 'International Water Association Publishing',
  year: 2026,
  link: '',
  isbn: '',
  eisbn: '',
  doi: '',
  featured: false
},
{
  id: 'book-03',
  title: 'Computational techniques for simulating and optimizing adsorption processes for (waste)water treatment',
  authors: ['A.Yadav', 'P.K. Labhasetwar'],
  image: '', // Replace with correct image if needed
  publisher: 'International Water Association Publishing',
  year: 2026,
  link: '',
  isbn: '',
  eisbn: '',
  doi: '',
  featured: false
}
]
};

export const patents = [
  {
  id: 'pat-05',
  title: 'An energy-efficient multi-stage modular membrane–crystallization system for zero liquid discharge in desalination and wastewater treatment',
  inventors: ['A. Yadav', 'A. K. Jha', 'B. Krishan', 'Nikhil'],
  patentNumber: 'IN2025110XXXXX',
  filingDate: 'xx–07–2025',
  status: 'Under preparation',
  link: 'https://ipindia.gov.in/patent-details'
},
  {
    id: 'pat-01',
    title: 'Multi-pass helical submerged membrane distillation module',
    inventors: ['A.Yadav', 'B. Krishna', 'Nikhil', 'P.K. Labhasetwar'],
    patentNumber: 'IN2025110XXXXX',
    filingDate: '15–06–2025',
    status: 'Filed',
    link: 'https://ipindia.gov.in/patent-details'
  },
  {
    id: 'pat-02',
    title: 'Twisted spacer filaments for low biofouling and scaling in the feed channel of membrane distillation',
    inventors: ['A.Yadav', 'A. Kumar', 'C.P. Singh', 'R.V. Patel'],
    patentNumber: 'IN2025110XXXXX',
    filingDate: '15–06–2025',
    status: 'Filed',
    link: 'https://ipindia.gov.in/patent-details'
  },
  {
    id: 'pat-03',
    title: 'A self-cleaning solar enabled smart device for real time surface water health monitoring',
    inventors: ['A.Yadav', 'E. Padhi', 'B. Krishna', 'Nikhil'],
    patentNumber: 'IN202511026994',
    filingDate: '24–03–2025',
    status: 'Published',
    link: 'https://ipindia.gov.in/patent-details'
  },
  {
    id: 'pat-04',
    title: 'Multi-pass concentric tubular module for membrane distillation',
    inventors: ['A.Yadav', 'R.V.P. Patel', 'B.M. Baladaniya', 'V.K. Shahi', 'P.K. Labhasetwar'],
    patentNumber: 'IN202411067163',
    filingDate: '05–09–2024',
    status: 'Filed',
    link: 'https://ipindia.gov.in/patent-details'
  },
];



export const invitedTalks = [
  {
    id: 'talk-01',
    title: 'Optimizing Fouling Resistant Membranes for High Flux Distillation',
    event: '2nd International Online Conference on Sustainable Technologies in Water Treatment and Desalination',
    speaker: 'Dr. A. Yadav',
    images:['/images/research/invited_talk/IT1(1).JPG','/images/research/invited_talk/IT1(2).JPG','/images/research/invited_talk/IT1(3).JPG','/images/research/invited_talk/IT1(4).JPG','/images/research/invited_talk/IT1(5).JPG'],
    date: 2022,
    mode:'Offline',
    location: 'Location of place',
    abstract: 'Presented recent developments in optimizing membranes to reduce fouling and enhance distillation flux.'
  },
  {
    id: 'talk-02',
    title: 'Fabrication of Fouling Resistant Membranes for High Flux Distillation',
    event: 'Technical Talk at Siksha \'O\' Anusandhan University',
    speaker: 'Dr. A. Yadav',
    date: 2022,
    location: 'Siksha \'O\' Anusandhan University, Odisha',
    abstract: 'Explored fabrication methods for advanced membranes used in distillation systems.'
  },
  {
    id: 'talk-03',
    title: 'Computational Fluid Dynamics for Engineering Applications',
    event: 'Guest Lecture at Raja Ram Institute of Management and Technology',
    speaker: 'Dr. A. Yadav',
    date: 2022,
    location: 'Raja Ram Institute of Management and Technology, Lucknow',
    abstract: 'Introduced applications of computational fluid dynamics in solving complex engineering problems, especially in water treatment.'
  },
  {
    id: 'talk-04',
    title: 'Membrane Distillation for High Saline Water and Wastewater Treatment: Recent Trends and Applications',
    event: 'Technical Seminar at Harcourt Butler Technical University',
    speaker: 'Dr. A. Yadav',
    date: 2023,
    location: 'Harcourt Butler Technical University, Kanpur',
    abstract: 'Discussed current trends and implementation strategies for membrane distillation in saline water treatment.'
  },
  {
    id: 'talk-05',
    title: 'Membrane Distillation Process for High Saline Water and Wastewater Treatment',
    event: 'Faculty Development Program on Green Energy Technology and Waste Management',
    speaker: 'Dr. A. Yadav',
    date: 2023,
    location: 'Jayaram Institute of Technology, Nagaur',
    abstract: 'Focused on practical applications of membrane distillation in green energy and waste reduction contexts.'
  },
  {
    id: 'talk-06',
    title: 'Membrane Distillation for High Saline Water and Wastewater Treatment: Recent Trends and Applications',
    event: 'International Conference on Recent Advances in Science, Technology, Humanities and Management',
    speaker: 'Dr. A. Yadav',
    date: 2023,
    location: 'International Conference on Recent Advances in Science, Technology, Humanities and Management (ICRASTHM)',
    abstract: 'Delivered insights on evolving techniques in saline and wastewater distillation technologies.'
  },
  {
    id: 'talk-07',
    title: 'Optimization of Fouling Resistant Membranes for High Flux',
    event: 'International Conference on Membranes and Water',
    speaker: 'Dr. A. Yadav',
    date: 2023,
    location: 'International Conference on Membranes and Water (ICMW 2023)',
    abstract: 'Explained the optimization techniques for high-performance anti-fouling membranes.'
  },
  {
    id: 'talk-08',
    title: 'Computational Fluid Dynamics and Molecular Modelling for Engineering Applications',
    event: 'Guest Lecture at Raja Ram Institute of Management and Technology',
    speaker: 'Dr. A. Yadav',
    date: 2022,
    location: 'Raja Ram Institute of Management and Technology, Lucknow',
    abstract: 'Demonstrated use of computational fluid dynamics and molecular modeling in environmental and water engineering applications.'
  }
];
